volumes:
  pgdata:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=db
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A checker worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A checker beat -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  redis:
    image: redis
