# Generated by Django 3.1.4 on 2020-12-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='URL address')),
                ('name', models.CharField(max_length=200, verbose_name='Site name')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Status code')),
                ('time', models.DateTimeField(verbose_name='Date and time of receiving status')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 address')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', related_query_name='status', to='sites.site')),
            ],
        ),
    ]
