# Generated by Django 3.1.4 on 2020-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20201204_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and time of receiving status'),
        ),
    ]
