# Generated by Django 3.1.4 on 2020-12-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20201205_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 address'),
        ),
    ]
